# -*- coding: utf-8 -*-
"""car price pridiction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qkqgMf7iJCJR_cUvWizBU7Q28TZNsuP
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

from google.colab import files
uploaded = files.upload()

#  Show Column Names (so you can find the target column)
df.columns

# Preprocessing - Handle Missing Values & Categorical Data
df = df.dropna()  # remove missing values
df = pd.get_dummies(df)  # convert text columns to numbers

df = pd.read_csv('dataset.csv')
df.head()

df.info()
df.isnull().sum()

# Separate features and target
X = df.drop(columns='price')
y = df['price']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier

# Create model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make Predictions and Show Accuracy
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Report:\n", classification_report(y_test, y_pred))